# Generated by Django 3.2.16 on 2023-04-29 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('towingapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptpart4',
            name='mileage_start',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
