# Generated by Django 3.2.5 on 2021-08-24 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('towingapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clock_in',
            name='author',
        ),
    ]
