# Generated by Django 3.2.16 on 2023-05-03 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('towingapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='criptionDEAD',
        ),
        migrations.AlterField(
            model_name='receipt',
            name='damage_type',
            field=models.CharField(blank=True, choices=[('scratched', 'Scratched'), ('damaged', 'Damaged'), ('accident', 'Accident'), ('broken', 'Broken'), ('none', 'None')], max_length=20, null=True),
        ),
    ]
