# Generated by Django 3.2.16 on 2023-04-06 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('towingapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clock_in',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clock_in',
            name='clock_status',
            field=models.CharField(choices=[('clock-in', 'Clock-in'), ('clock-out', 'Clock-out')], default='clock-in', max_length=10),
        ),
    ]
