# Generated by Django 3.2.5 on 2021-08-24 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('towingapp', '0002_remove_clock_in_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='clock_in',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='towingapp.myuser'),
            preserve_default=False,
        ),
    ]
