# Generated by Django 3.2.16 on 2023-04-14 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('towingapp', '0002_auto_20230406_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='towingapp.mensaje', verbose_name='Reply To'),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='recipient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL, verbose_name='Recipient'),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='sender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Sender'),
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Text')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies_sent', to='towingapp.mensaje', verbose_name='Message')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies_sent', to=settings.AUTH_USER_MODEL, verbose_name='Sender')),
            ],
        ),
    ]
