# Generated by Django 3.2.5 on 2021-08-24 15:35

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('towingapp', '0003_clock_in_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clock_in',
            name='author',
            field=models.ForeignKey(default=django.contrib.auth.models.AbstractUser, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
