# Generated by Django 3.2.5 on 2021-09-10 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('towingapp', '0006_alter_clock_in_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
